---
- name: update package lists
  tags:
    - base
  apt:
    update_cache: true

- name: install common packages
  tags:
    - base
  apt: pkg={{ item }} state=present
  with_items:
    - byobu
    - git
    - htop
    - jq
    - tmux
    - tree
    - lm-sensors
    - yamllint

- name: install additional disk monitoring packages
  tags:
    - base
  when: base_disk_monitoring
  apt: pkg={{ item }} state=present
  with_items:
    - zfsutils-linux
    - hddtemp
    - smartmontools
    - nvme-cli

- name: upgrade all packages
  tags:
    - base
  when: base_dist_upgrade
  apt:
    upgrade: dist
