---
language: python
os:
  - linux
dist: xenial
before_install:
  - pip install yamllint
script:
  # Sanity check all YAML files:
  #   - ignore line-length lint
  #   - ignore ansible vault-encrypted files
  - diff -u <(echo -n) <(yamllint -f parsable ./ansible | grep -v "line-length" | grep -E -v "[rtorrent_exporter,traefik]/vars/main.yml")
