---
- name: add unifi apt key
  tags:
    - unifi
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: C0A52C50

- name: add unifi apt repository
  tags:
    - unifi
  apt_repository:
    repo: "deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti"
    state: present

- name: install haveged and unifi controller
  tags:
    - unifi
  apt:
    pkg:
      - haveged
      - unifi
    state: present
    update_cache: true

- name: start unifi service
  tags:
    - unifi
  service:
    name: unifi
    state: started
    enabled: true
