---
- name: download and checksum rtorrent_exporter {{ host_golang_arch }} binary
  tags:
    - rtorrent_exporter
  get_url:
    url: "https://mdlayher.nyc3.digitaloceanspaces.com/bin/rtorrent_exporter_{{ host_golang_arch }}"
    dest: "/tmp/rtorrent_exporter"
    checksum: "sha256:{{ rtorrent_exporter_sha256 }}"

- name: create rtorrent_exporter user
  tags:
    - rtorrent_exporter
  user:
    name: rtorrent_exporter
    shell: "/bin/false"
    comment: "rtorrent_exporter service user"

- name: check if rtorrent_exporter service exists
  tags:
    - rtorrent_exporter
  stat:
    path: "/etc/systemd/system/rtorrent_exporter.service"
  register: checked

- name: stop rtorrent_exporter service if it exists
  tags:
    - rtorrent_exporter
  when: checked.stat.exists
  service:
    name: rtorrent_exporter
    state: stopped

- name: copy rtorrent_exporter binary to {{ host_bin_path }}
  tags:
    - rtorrent_exporter
  command: "cp /tmp/rtorrent_exporter {{ host_bin_path }}/"

- name: set permissions on rtorrent_exporter binary
  tags:
    - rtorrent_exporter
  file:
    path: "{{ host_bin_path }}/rtorrent_exporter"
    owner: rtorrent_exporter
    group: rtorrent_exporter
    mode: 0755

- name: create rtorrent_exporter systemd unit
  tags:
    - rtorrent_exporter
  template:
    src: rtorrent_exporter.service.j2
    dest: "/etc/systemd/system/rtorrent_exporter.service"

- name: reload systemd configurations
  tags:
    - rtorrent_exporter
  command: "systemctl daemon-reload"

- name: start rtorrent_exporter service
  tags:
    - rtorrent_exporter
  service:
    name: rtorrent_exporter
    state: started
    enabled: true

- name: remove temporary files
  tags:
    - rtorrent_exporter
  file:
    path: "/tmp/rtorrent_exporter"
    state: absent
