---
- name: update package lists
  tags:
    - homeassistant
  apt:
    update_cache: true

- name: install python3 and dependencies
  tags:
    - homeassistant
  apt: pkg={{ item }} state=present
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - libffi-dev
    - libssl-dev

- name: install homeassistant using pip
  tags:
    - homeassistant
  pip:
    name: homeassistant
    executable: /usr/bin/pip3
    state: latest

- name: create homeassistant user
  tags:
    - homeassistant
  user:
    name: homeassistant
    shell: "/bin/false"
    comment: "homeassistant service user"
    # Groups recommended by:
    # https://www.home-assistant.io/docs/installation/raspberry-pi/.
    groups:
      - "dialout"
      - "gpio"
      - "i2c"

- name: check if homeassistant service exists
  tags:
    - homeassistant
  stat:
    path: "/etc/systemd/system/homeassistant.service"
  register: svccheck

- name: stop homeassistant service if it exists
  tags:
    - homeassistant
  when: svccheck.stat.exists
  service:
    name: homeassistant
    state: stopped

- name: create homeassistant systemd unit
  tags:
    - homeassistant
  template:
    src: homeassistant.service.j2
    dest: "/etc/systemd/system/homeassistant.service"

- name: reload systemd configurations
  tags:
    - homeassistant
  command: "systemctl daemon-reload"

- name: start homeassistant service
  tags:
    - homeassistant
  service:
    name: homeassistant
    state: started
    enabled: true
