---
# Prometheus version and checksum configuration.
prometheus_version: "2.11.0"
prometheus_sha256: "9705ee80713809b29995e94ce8786a901c046c9b3fd555aac965bf50a28bc2e3"
# Prometheus configuration and data storage locations.
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus alerting configuration.
prometheus_alertmanagers:
  - "monitnerr-1:9093"
# Prometheus jobs configuration.
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "servnerr-3:9162"
      - "nerr-3:9162"
  - job: "hdhomerun"
    targets:
      - "hdhomerun"
    relabel_target: "servnerr-3:9137"
  - job: "node"
    targets:
      - "monitnerr-1:9100"
      - "nerr-3:9100"
      - "routnerr-1:9100"
      - "servnerr-3:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "servnerr-3:9090"
  - job: "rtorrent"
    scrape_interval: "30s"
    targets:
      - "servnerr-3:9135"
  - job: "snmp_exporter"
    targets:
      - "servnerr-3:9116"
  - job: "snmp"
    path: "/snmp"
    params:
      module: [if_mib]
    targets:
      - "routnerr-1"
      - "switch-livingroom01"
      - "switch-office01"
      - "ap-livingroom01"
    relabel_target: "servnerr-3:9116"
  - job: "traefik"
    targets:
      - "servnerr-3:8080"
  - job: "wireguard"
    targets:
      - "routnerr-1:9586"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
