---
# Prometheus version and checksum configuration
prometheus_version: "2.7.1"
prometheus_sha256: "7837cfd6b5af63c07cadfa2b3118f0a43e43e8a6e6d596425cb23b45855b7db0"
# Prometheus configuration and data storage locations
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus jobs configuration
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "192.168.1.4:9162"
  - job: "hdhomerun"
    targets:
      - "192.168.1.8"
    relabel_target: "192.168.1.4:9137"
  - job: "mdlayher.com"
    scheme: "https"
    targets:
      - "mdlayher.com"
  - job: "node"
    targets:
      - "192.168.1.4:9100"
      - "192.168.1.5:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "192.168.1.4:9090"
  - job: "snmp_exporter"
    targets:
      - "192.168.1.4:9116"
  - job: "snmp"
    path: "/snmp"
    params:
      module: [if_mib]
    targets:
      - "192.168.1.1"
      - "192.168.1.2"
      - "192.168.1.3"
      - "192.168.1.20"
    relabel_target: "192.168.1.4:9116"
  - job: "traefik"
    targets:
      - "192.168.1.4:8080"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
