---
# Prometheus version and checksum configuration.
prometheus_version: "2.14.0"
prometheus_sha256: "ddf47223ec716594254df110ee26ad52e66d7d4471ae8edbf9020087396861e5"
# Prometheus alerting configuration.
prometheus_alertmanagers:
  - "monitnerr-1:9093"
# Prometheus jobs configuration.
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "servnerr-3:9162"
      - "nerr-3:9162"
  - job: "blackbox_http_2xx"
    path: "/probe"
    params:
      module: [http_2xx]
    targets:
      - "http://servnerr-3:8080"
      - "https://mdlayher.com"
      - "https://grafana.servnerr.com"
      # TODO: move onto server and re-enable.
      # - "https://homeassistant.servnerr.com"
    relabel_target: "monitnerr-1:9115"
  - job: "blackbox_http_401"
    path: "/probe"
    params:
      module: [http_401]
    targets:
      - "https://alertmanager.servnerr.com"
      - "https://plex.servnerr.com"
      - "https://prometheus.servnerr.com"
    relabel_target: "monitnerr-1:9115"
  - job: "blackbox_ssh"
    path: "/probe"
    params:
      module: [ssh_banner]
    targets:
      - "monitnerr-1:22"
      - "nerr-3:22"
      - "routnerr-2:22"
      - "servnerr-3:22"
      - "unifi.servnerr.com:22"
    relabel_target: "monitnerr-1:9115"
  - job: "blackbox_exporter"
    targets:
      - "monitnerr-1:9115"
  - job: "coredns"
    targets:
      - "routnerr-2:9153"
  - job: "hdhomerun"
    targets:
      - "hdhomerun"
    relabel_target: "servnerr-3:9137"
  - job: "loki"
    targets:
      - "servnerr-3:3100"
  - job: "minecraft"
    targets:
      - "servnerr-3:9225"
  - job: "node"
    targets:
      - "monitnerr-1:9100"
      - "nerr-3:9100"
      - "routnerr-2:9100"
      - "servnerr-3:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "servnerr-3:9090"
  - job: "promtail"
    targets:
      - "servnerr-3:9080"
  - job: "rtorrent"
    scrape_interval: "30s"
    targets:
      - "servnerr-3:9135"
  - job: "snmp_exporter"
    targets:
      - "servnerr-3:9116"
  - job: "snmp"
    path: "/snmp"
    params:
      module: [if_mib]
    targets:
      - "switch-livingroom01"
      - "switch-office01"
      - "ap-livingroom01"
    relabel_target: "servnerr-3:9116"
  - job: "traefik"
    targets:
      - "servnerr-3:8080"
# TODO: temporarily disabled while I get this working on NixOS.
#  - job: "wireguard"
#    targets:
#      - "routnerr-2:9586"
# Static configuration.
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
prometheus_external_url: "https://prometheus.servnerr.com"
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
