---
# Prometheus version and checksum configuration
prometheus_version: "2.7.1"
prometheus_sha256: "7837cfd6b5af63c07cadfa2b3118f0a43e43e8a6e6d596425cb23b45855b7db0"
# Prometheus configuration and data storage locations
prometheus_config: "/etc/prometheus"
prometheus_data: "/var/lib/prometheus"
# Prometheus jobs configuration
prometheus_jobs:
  - job: "apcupsd"
    targets:
      - "servnerr-3:9162"
  - job: "hdhomerun"
    targets:
      - "hdhomerun"
    relabel_target: "servnerr-3:9137"
  - job: "node"
    targets:
      - "servnerr-3:9100"
      - "nerr-2:9100"
  - job: "prometheus"
    scrape_interval: "5s"
    targets:
      - "servnerr-3:9090"
  - job: "snmp_exporter"
    targets:
      - "servnerr-3:9116"
  - job: "snmp"
    path: "/snmp"
    params:
      module: [if_mib]
    targets:
      - "routnerr-1"
      - "switch-livingroom01"
      - "switch-office01"
      - "ap-livingroom01"
    relabel_target: "servnerr-3:9116"
  - job: "traefik"
    targets:
      - "servnerr-3:8080"
# Static configuration.
prometheus_dir: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_tmp: "/tmp/{{ prometheus_dir }}"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
prometheus_tgz: "/tmp/prometheus.tar.gz"
