---
- name: add grafana apt key
  tags:
    - grafana
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: add grafana apt repository
  tags:
    - grafana
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: install grafana
  tags:
    - grafana
  apt:
    pkg: grafana
    state: present
    update_cache: true

- name: start grafana service
  tags:
    - grafana
  service:
    name: grafana-server
    state: started
    enabled: true
