---
- name: check if installing a different version of spotifyd
  tags:
    - spotifyd
  shell: "cat {{ spotifyd_config }}/.sha256"
  ignore_errors: true
  register: checksum

- name: determine if spotifyd {{ spotifyd_version}} should be installed
  tags:
    - spotifyd
  set_fact:
    spotifyd_install: (checksum.stdout.find(spotifyd_sha256) == -1) or (spotifyd_force is defined)

- name: download and checksum spotifyd {{ spotifyd_version }} tarball
  tags:
    - spotifyd
  when: spotifyd_install
  get_url:
    url: "{{ spotifyd_url }}"
    dest: "{{ spotifyd_tgz }}"
    checksum: "sha256:{{ spotifyd_sha256 }}"

- name: unpack spotifyd tarball
  tags:
    - spotifyd
  when: spotifyd_install
  unarchive:
    src: "{{ spotifyd_tgz }}"
    dest: "/tmp/"
    copy: false

- name: check if spotifyd service exists
  tags:
    - spotifyd
  stat:
    path: "/etc/systemd/user/spotifyd.service"
  register: checked

- name: stop spotifyd service if it exists
  tags:
    - spotifyd
  when: checked.stat.exists
  become: true
  become_user: matt
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"
  service:
    name: spotifyd
    state: stopped
    user: true

- name: copy spotifyd binary to {{ host_bin_path }}
  tags:
    - spotifyd
  when: spotifyd_install
  command: "cp /tmp/spotifyd {{ host_bin_path }}/"

- name: set permissions on spotifyd binary
  tags:
    - spotifyd
  when: spotifyd_install
  file:
    path: "{{ host_bin_path }}/spotifyd"
    owner: matt
    group: matt
    mode: 0755

- name: create spotifyd config directory
  tags:
    - spotifyd
  when: spotifyd_install
  file:
    path: "{{ spotifyd_config }}"
    state: directory
    owner: matt
    group: matt
    mode: 0755

- name: create spotifyd configuration
  tags:
    - spotifyd
  template:
    src: spotifyd.conf.j2
    dest: "{{ spotifyd_config }}/spotifyd.conf"
    owner: matt
    group: matt
    mode: 0600

- name: create spotifyd data directory
  tags:
    - spotifyd
  when: spotifyd_install
  file:
    path: "{{ spotifyd_data }}"
    state: directory
    owner: matt
    group: matt
    mode: 0755

- name: create spotifyd systemd unit
  tags:
    - spotifyd
  template:
    src: spotifyd.service.j2
    dest: "/etc/systemd/user/spotifyd.service"

- name: reload systemd configurations
  tags:
    - spotifyd
  become: true
  become_user: matt
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"
  command: "systemctl --user daemon-reload"

- name: start spotifyd service
  tags:
    - spotifyd
  become: true
  become_user: matt
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"
  service:
    name: spotifyd
    state: started
    enabled: true
    user: true

- name: remove temporary files
  tags:
    - spotifyd
  when: spotifyd_install
  file:
    path: "/tmp/spotifyd"
    state: absent

- name: create checksum file for spotifyd {{ spotifyd_version }}
  tags:
    - spotifyd
  when: spotifyd_install
  template:
    src: sha256.j2
    dest: "{{ spotifyd_config }}/.sha256"
