---
- name: download and checksum arris_exporter binary
  tags:
    - arris_exporter
  get_url:
    url: "{{ arris_exporter_url }}"
    dest: "/tmp/arris_exporter"
    checksum: "sha256:{{ arris_exporter_sha256 }}"

- name: create arris_exporter user
  tags:
    - arris_exporter
  user:
    name: arris_exporter
    shell: "/bin/false"
    comment: "arris_exporter service user"

- name: check if arris_exporter service exists
  tags:
    - arris_exporter
  stat:
    path: "/etc/systemd/system/arris_exporter.service"
  register: checked

- name: stop arris_exporter service if it exists
  tags:
    - arris_exporter
  when: checked.stat.exists
  service:
    name: arris_exporter
    state: stopped

- name: copy arris_exporter binary to /usr/local/bin
  tags:
    - arris_exporter
  command: "cp /tmp/arris_exporter /usr/local/bin/"

- name: set permissions on arris_exporter binary
  tags:
    - arris_exporter
  file:
    path: "/usr/local/bin/arris_exporter"
    owner: arris_exporter
    group: arris_exporter
    mode: 0755

- name: create arris_exporter systemd unit
  tags:
    - arris_exporter
  template:
    src: arris_exporter.service.j2
    dest: "/etc/systemd/system/arris_exporter.service"

- name: reload systemd configurations
  tags:
    - arris_exporter
  command: "systemctl daemon-reload"

- name: start arris_exporter service
  tags:
    - arris_exporter
  service:
    name: arris_exporter
    state: started
    enabled: yes

- name: remove temporary files
  tags:
    - arris_exporter
  file:
    path: "/tmp/arris_exporter"
    state: absent
