---
node_exporter_textfile_dir: "/var/lib/node_exporter"
# Version configuration.
node_exporter_version: "0.18.1"
node_exporter_sha256: "b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"
# Static configuration.
node_exporter_dir: "node_exporter-{{ node_exporter_version }}.linux-amd64"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_dir }}.tar.gz"
node_exporter_tgz: "/tmp/node_exporter.tgz"
