---
- name: download and checksum wgipamd {{ host_golang_arch }} binary
  tags:
    - wgipamd
  get_url:
    url: "https://mdlayher.nyc3.digitaloceanspaces.com/bin/wgipamd_{{ host_golang_arch }}"
    dest: "/tmp/wgipamd"
    checksum: "sha256:{{ wgipamd_sha256 }}"

- name: create wgipamd user
  tags:
    - wgipamd
  user:
    name: wgipamd
    shell: "/bin/false"
    comment: "wgipamd service user"

- name: check if wgipamd service exists
  tags:
    - wgipamd
  stat:
    path: "/etc/systemd/system/wgipamd.service"
  register: checked

- name: stop wgipamd service if it exists
  tags:
    - wgipamd
  when: checked.stat.exists
  service:
    name: wgipamd
    state: stopped

- name: copy wgipamd binary to {{ host_bin_path }}
  tags:
    - wgipamd
  command: "cp /tmp/wgipamd {{ host_bin_path }}/"

- name: set permissions on wgipamd binary
  tags:
    - wgipamd
  file:
    path: "{{ host_bin_path }}/wgipamd"
    owner: wgipamd
    group: wgipamd
    mode: 0755

- name: grant capabilities to wgipamd binary
  tags:
    - wgipamd
  capabilities:
    path: "{{ host_bin_path }}/wgipamd"
    capability: "cap_net_bind_service+ep"
    state: present

- name: create wgipamd config and data directories
  tags:
    - wgipamd
  file:
    path: "{{ item }}"
    state: directory
    owner: wgipamd
    group: wgipamd
    mode: 0755
  with_items:
    - "{{ wgipamd_config }}"
    - "{{ wgipamd_data }}"

- name: create wgipamd configuration
  tags:
    - wgipamd
  template:
    src: wgipamd.yaml.j2
    dest: "{{ wgipamd_config }}/wgipamd.yaml"
  with_items: "{{ wgipamd_interfaces }}"

- name: create wgipamd systemd unit
  tags:
    - wgipamd
  template:
    src: wgipamd.service.j2
    dest: "/etc/systemd/system/wgipamd.service"

- name: reload systemd configurations
  tags:
    - wgipamd
  command: "systemctl daemon-reload"

- name: start wgipamd service
  tags:
    - wgipamd
  service:
    name: wgipamd
    state: started
    enabled: true

- name: remove temporary files
  tags:
    - wgipamd
  file:
    path: "/tmp/wgipamd"
    state: absent
