---
- name: install qemu, KVM, libvirt, and utilities
  tags:
    - kvm
  apt:
    pkg: "{{item}}"
    state: installed
  with_items:
    - qemu-kvm
    - libvirt-bin
    - virtinst
    - bridge-utils
    - cpu-checker

- name: check for KVM acceleration capabilities
  tags:
    - kvm
  command: kvm-ok

- name: check for bridge br0
  tags:
    - kvm
  command: brctl show br0
  register: brcheck

- name: create bridge br0 if it doesn't exist
  tags:
    - kvm
  command: brctl addbr br0
  when: brcheck.stdout.find("No such device") != -1

- name: insert bridge configuration template
  tags:
    - kvm
  blockinfile:
    dest: "/etc/netplan/01-netcfg.yaml"
    marker: "# {mark} ansible-managed KVM br0 template"
    block: |
      {{ '#' }} # Replace Ethernet interface name as appropriate.
      {{ '# '}} # ethernets:
      {{ '#' }} #   eth0:
      {{ '#' }} #     dhcp4: false
      {{ '#' }} #     dhcp6: false
      {{ '#' }} #     optional: true
      {{ '#' }} #   bridges:
      {{ '#' }} #     br0:
      {{ '#' }} #       interfaces: [eth0]
      {{ '#' }} #       dhcp4: true
      {{ '#' }} #       dhcp6: true
      {{ '#' }} #       accept-ra: true
      {{ '#' }} #       optional: true
