---
amd64:
  hosts:
    servnerr-3:
    nerr-3:
  vars:
    host_bin_path: "/usr/local/bin"
    host_golang_arch: "amd64"
    host_xdg: "/run/user/1000"
    base_disk_monitoring: true
    base_dist_upgrade: true
    node_exporter_sha256: "b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"
    node_exporter_use_textfile: true
    promtail_sha256: "0354e2298b154c81286075c44dfbceda801c362de98e03a2c94e9edf22fd86ae"
server:
  hosts:
    servnerr-3:
      apcupsd_battery_date: "05/19/17"
      loki_sha256: "e6e48ed3d7b92f9ed657078743cee80a25559fb977d00203d1b1676ad63c5d38"
      rtorrent_exporter_sha256: "7b143833b5a41e3e93938902ba96d6c2643a6b50b80cfcb54eba0c88846b7eb1"
workstation:
  hosts:
    nerr-3:
      apcupsd_battery_date: "11/29/2016"
monitor:
  hosts:
    monitnerr-1:
      host_bin_path: "/usr/local/bin"
      host_golang_arch: "armv7"
      base_disk_monitoring: false
      base_dist_upgrade: true
      alertmanager_sha256: "d0db8003279ca8cdb74150ebcf90dae6c9974bc5ac3aa7c220dcf5ea430636a2"
      blackbox_exporter_sha256: "1aa3934b1bcd03ae5c206b4788dff3c931a0c8643459f276205e86ef0f056bfc"
      node_exporter_sha256: "5de85067f44b42b22d62b2789cb1a379ff5559649b99795cd1ba0c144b512ad0"
      node_exporter_use_textfile: false
unifi:
  hosts:
    unifi.servnerr.com:
      base_disk_monitoring: false
      base_dist_upgrade: true
