---
amd64:
  hosts:
    servnerr-3:
    nerr-3:
  vars:
    host_bin_path: "/usr/local/bin"
    host_golang_arch: "amd64"
    node_exporter_sha256: "b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"
    node_exporter_use_textfile: true
server:
  hosts:
    servnerr-3:
      apcupsd_battery_date: "05/19/17"
      rtorrent_exporter_sha256: "7b143833b5a41e3e93938902ba96d6c2643a6b50b80cfcb54eba0c88846b7eb1"
workstation:
  hosts:
    nerr-3:
      apcupsd_battery_date: "11/29/2016"
router:
  hosts:
    routnerr-1:
      host_bin_path: "/usr/bin"
      host_golang_arch: "mips64"
      node_exporter_sha256: "c2721c1b85e3024e61f37fb2dc44a57f6d4eed8cc0576185a1dedea20e36fb31"
      node_exporter_use_textfile: false
      # /config persists between firmware upgrades.
      wgipamd_config: "/config/user-data/wgipamd"
      wgipamd_data: "/config/user-data/wgipamd"
      # Interface address serving configurations.
      wgipamd_interfaces:
        interfaces:
          - name: "wg0"
            subnets:
              # In this early testing phase, support a single machine lease.
              - "192.168.20.10/32"
              - "2604:6c4a:787f:d220::10/128"
      wgipamd_sha256: "5c7600ee81b2c05b2fbd7993cbf5df0c7788729387197ad75c7cb2fa420a3a93"
      wireguard_exporter_sha256: "4a49b28a7661f964c2f2f9030fdb53c1171f228e1602c2a3c95b77c6ad824f47"
unifi:
  hosts:
    unifi.servnerr.com:
