---
- name: check if installing a different version of loki
  tags:
    - loki
  shell: "cat {{ loki_config }}/.sha256"
  ignore_errors: true
  register: checksum

- name: determine if loki should be installed
  tags:
    - loki
  set_fact:
    loki_install: (checksum.stdout.find(loki_sha256) == -1) or (loki_force is defined)

- name: download and checksum loki {{ host_golang_arch }} binary
  tags:
    - loki
  when: loki_install
  get_url:
    url: "https://mdlayher.nyc3.digitaloceanspaces.com/bin/loki_{{ host_golang_arch }}"
    dest: "/tmp/loki"
    checksum: "sha256:{{ loki_sha256 }}"

- name: create loki user
  tags:
    - loki
  when: loki_install
  user:
    name: loki
    shell: "/bin/false"
    comment: "loki service user"

- name: check if loki service exists
  tags:
    - loki
  stat:
    path: "/etc/systemd/system/loki.service"
  register: svccheck

- name: stop loki service if it exists
  tags:
    - loki
  when: svccheck.stat.exists
  service:
    name: loki
    state: stopped

- name: copy loki binary to {{ host_bin_path }}
  tags:
    - loki
  when: loki_install
  command: "cp /tmp/loki {{ host_bin_path }}/"

- name: set permissions on loki binary
  tags:
    - loki
  when: loki_install
  file:
    path: "{{ host_bin_path }}/loki"
    owner: loki
    group: loki
    mode: 0755

- name: create loki directories
  tags:
    - loki
  when: loki_install
  file:
    path: "{{ item }}"
    state: directory
    owner: loki
    group: loki
    mode: 0755
  with_items:
    - "{{ loki_config }}"
    - "{{ loki_data }}"

- name: create loki configuration
  tags:
    - loki
  template:
    src: loki.yml.j2
    dest: "{{ loki_config }}/loki.yml"

- name: create loki systemd unit
  tags:
    - loki
  template:
    src: loki.service.j2
    dest: "/etc/systemd/system/loki.service"

- name: reload systemd configurations
  tags:
    - loki
  command: "systemctl daemon-reload"

- name: start loki service
  tags:
    - loki
  service:
    name: loki
    state: started
    enabled: true

- name: remove temporary loki files
  tags:
    - loki
  when: loki_install
  file:
    path: "/tmp/loki"
    state: absent

- name: create checksum file for loki at current git revision
  tags:
    - loki
  when: loki_install
  template:
    src: sha256.j2
    dest: "{{ loki_config }}/.sha256"
