---
# Go version to install and its tarball checksum.
golang_version: "go1.13.7"
golang_sha256: "b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3"
# Personal Go configuration.
golang_user: "matt"
golang_user_home: "/home/{{ golang_user }}"
golang_personal_gopath: "github.com/mdlayher"
# Static configuration.
golang_url: "https://storage.googleapis.com/golang/{{ golang_version }}.linux-amd64.tar.gz"
golang_tgz: "/tmp/golang.tar.gz"
golang_root: "/usr/local/go"
